#ifndef _KEY_MAP_INCLUDED_
#define _KEY_MAP_INCLUDED_

#include "keydef.h"

uint16_t KeyMap[128] =
{
  KEY_UP_ARROW,		//	  80
  KEY_NUM,		//	  81
  KEY_END,		//	  82
  KEY_HOME,		//	  83
  KEY_NULL,		//	  84
  KEY_PAGE_DOWN,	//	  85
  KEY_PAGE_UP,		//	  86
  KEY_DOWN_ARROW,	//	  87
  KEY_NULL,		//	  88
  KEY_PRINT,		//	  89
  KEY_RIGHT_ARROW,	//	  8a
  KEY_INSERT,		//	  8b
  KEY_NULL,		//	  8c
  KEY_NULL,		//	  8d
  KEY_NULL,		//	  8e
  KEY_NULL,		//	  8f
  KEY_GREEN,		//	  90
  KEY_BLACK,		//	  91
  KEY_YELLOW,		//	  92
  KEY_NULL,		//	  93
  KEY_LIGHT_BLUE,	//	  94
  KEY_NULL,		//	  95
  KEY_LEFT_SCREEN,	//	  96
  KEY_DARK_BLUE,	//	  97
  KEY_NULL,		//	  98
  KEY_NULL,		//	  99
  KEY_WHITE,		//	  9a
  KEY_RIGHT_SCREEN,	//	  9b
  KEY_LEFT_ARROW,	//	  9c
  KEY_HOUSE,		//	  9d
  KEY_NULL,		//	  9e
  KEY_DELETE,		//	  9f
  KEY_F4,		//	  a0
  KEY_F3,		//	  a1
  KEY_F2,		//	  a2
  KEY_F1,		//	  a3
  KEY_F8,		//	  a4
  KEY_F7,		//	  a5
  KEY_F6,		//	  a6
  KEY_F5,		//	  a7
  KEY_F12,		//	  a8
  KEY_F11,		//	  a9
  KEY_F10,		//	  aa
  KEY_F9,		//	  ab
  KEY_NULL,		//	  ac
  KEY_BREAK,		//	  ad
  KEY_SCROLL_LOCK,	//	  ae
  KEY_NUM_LOCK,		//	  af
  KEY_NULL,		//	  b0
  KEY_NULL,		//	  b1
  KEY_NULL,		//	  b2
  KEY_NULL,		//	  b3
  KEY_NULL,		//	  b4
  KEY_NULL,		//	  b5
  KEY_NULL,		//	  b6
  KEY_NULL,		//	  b7
  KEY_LARGE_LEFT_BUTTON, //       b8
  KEY_NULL,		//	  b9
  KEY_NULL,		//	  ba
  KEY_NULL,		//	  bb
  KEY_SMALL_LEFT_BUTTON, //  	  bc
  KEY_ESC,		//	  bd
  KEY_NULL,		//	  be
  KEY_NULL,		//	  bf
  KEY_E,		//	  c0
  KEY_W,		//	  c1
  KEY_Q,		//	  c2
  KEY_TAB,		//	  c3
  KEY_U,		//	  c4
  KEY_Y,		//	  c5
  KEY_T,		//	  c6
  KEY_R,		//	  c7
  KEY_OPEN_BRACKET,	//	  c8
  KEY_P,		//	  c9
  KEY_O,		//	  ca
  KEY_I,		//	  cb
  KEY_A,		//	  cc
  KEY_CAPS_LOCK,	//	  cd
  KEY_BACKSLASH,	//	  ce
  KEY_CLOSE_BRACKET,	//	  cf
  KEY_2,		//	  d0
  KEY_1,		//	  d1
  KEY_GRAVE,		//	  d2
  KEY_NULL,		//	  d3
  KEY_6,		//	  d4
  KEY_5,		//	  d5
  KEY_4,		//	  d6
  KEY_3,		//	  d7
  KEY_0,		//	  d8
  KEY_9,		//	  d9
  KEY_8,		//	  da
  KEY_7,		//	  db
  KEY_BACKSPACE,	//	  dc
  KEY_NULL,		//	  dd
  KEY_EQUALS,		//	  de
  KEY_HYPHEN,		//	  df
  KEY_N,		//	  e0
  KEY_B,		//	  e1
  KEY_V,		//	  e2
  KEY_C,		//	  e3
  KEY_FORWARD_SLASH,	//	  e4
  KEY_PERIOD,		//	  e5
  KEY_COMMA,		//	  e6
  KEY_M,		//	  e7
  KEY_NULL,		//	  e8
  KEY_LEFT_CTRL,	//	  e9
  KEY_RIGHT_SHIFT,	//	  ea
  KEY_RED,		//	  eb
  KEY_VIOLET,		//	  ec
  KEY_NULL,		//	  ed
  KEY_SPACE,		//	  ee
  KEY_LEFT_ALT,		//	  ef
  KEY_G,		//	  f0
  KEY_F,		//	  f1
  KEY_D,		//	  f2
  KEY_S,		//	  f3
  KEY_L,		//	  f4
  KEY_K,		//	  f5
  KEY_J,		//	  f6
  KEY_H,		//	  f7
  KEY_ENTER,		//	  f8
  KEY_NULL,		//	  f9
  KEY_APOSTROPHE,	//	  fa
  KEY_SEMICOLON,	//	  fb
  KEY_X,		//	  fc
  KEY_Z,		//	  fd
  KEY_NULL,		//	  fe
  KEY_LEFT_SHIFT,	//	  ff
};
#endif		// _KEY_MAP_INCLUDED_